spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoppee
    username: postgres
    password: 09122002
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088




